#Location: ~/.config/starship.toml
#What_is_starship: https://starship.rs/

add_newline = false
command_timeout = 2000

format = """ $env_var$os$username$hostname$kubernetes$directory$git_branch$git_status$python$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[//](black bold) [ ](green)"
error_symbol = "[//](black bold) [ ](red)"

# ╭╴ ╰─

[env_var]
symbol = " "
variable = 'SHELL'
format = "$symbol"
disabled = true


#warp-Drop ugly default prompt characters
#success_symbol = ""
#error_symbol = ""

# ---

[os]
format = '[$symbol](bold #1793d1) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

# ---y

# Shows the username
[username]
style_user = 'mauve'
style_root = 'red bold'
format = '[//](black bold) [$user]($style) ' # 2883ff
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = true
format = '[//](black bold) [$hostname](bold mauve) '
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
# read_only_style = '197'
read_only = '  '
format = '[//](black bold) [$path]($style)[$read_only]($read_only_style) '
style = '#7ed1fb' # yellow bold


# Shows current git branch
[git_branch]
# symbol = ' '
symbol = ' '
format = '[//](black bold) [$symbol\[$branch\]]($style) '
# truncation_length = 0
# truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
disabled = true
format = '[ $all_status $ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
symbol = '󰌠'
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = '[//](black bold) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '


[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

